server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/clients/**
        - id: item-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/items/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
